# Generated by Django 4.2.5 on 2023-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_codec',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_dimension_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_dimension_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_upload_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
