# Generated by Django 4.2.5 on 2023-09-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startube', '0002_asset_asset_codec_asset_asset_dimension_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=500)),
                ('video_public', models.BooleanField(default=True)),
                ('video_number_of_views', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_video',
            field=models.ForeignKey(blank=True, default=123, on_delete=django.db.models.deletion.CASCADE, to='startube.video'),
            preserve_default=False,
        ),
    ]
