# Generated by Django 4.2.5 on 2023-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startube', '0005_video_video_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_number_of_views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
